name: rkmaul_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
